### DISCUSSION TITLE
2/4/6 CH Energy Meter Made For ESPHome

### DISCUSSION THREAD

**Discussion by Roving-Ronin** [athom-tech/esp32-configs#14] [General]
Hi @tarontop @athom-tech 

Any idea if these new Energy Meter can be run on 12/24/48V DC power sources?
These units would be a great option for people wanting to monitor power/energy etc in places like caravans (12/24V DC) or remote sites operating on 48V DC, that all have things like solar and batteries that are wanted to be monitored.

BTW are there any 'spare' GPIO pin that could be used to create UART and wire in things like Victron MPPT also ?

Thanks.

**Comment by tarontop** [comment]
The current hardware circuit does not support DC voltage measurement. The PCB board leads to 6 available GPIOs (IO2, IO3, IO4, IO5, IO6, IO18)

**Reply by Roving-Ronin** [reply]
Is DC support possible by modifications, or might you release a DC version?

PS. Could you take a look at those Pull Requests on here (and the ESP8285 repo) ?

**Reply by Roving-Ronin** [reply]
@tarontop Aiden,

Some feedback in regards this new product, after helping a friend (who has electrician experience) set this up.
Whilst not a truly 3 phase ready energy monitor, given it is unable to sample all 3p for voltage, frequency and power factor (and take this into account), it is for now being used to monitor the 3p grid feed and 3 internal circuits around the house (of 36).

He received PCB v1.1 (I assume this is latest?):
![image](https://github.com/user-attachments/assets/218c615e-e105-4afe-a824-eae1cac815cf)

1) After correctly connecting up the 6 CT's is was found that 4 of the 6 where producing negative readings. Referring to the labelling on the CT's for direction they should be installed and confirming the correct wiring into the wiring blocks, it was determined that there is an issue with them. Logic would say that it is the labelling on the CT's that is incorrect on some.

2) Looking at the custom component you've written and the yaml, I note that you have a 'total_energy' and 'total_power' sensor.  IMHO these sensors have very little use/value, and need to look at the usage scenarios of this device. 
Typically most people are looking too see what Power (w) and Energy (kWh) they are using so they can use this to monitor but also work out if/when/where (aided by smart plug) it is being used and then stop it or move to cheaper time of usage. To do this they will be connecting the Energy_Monitor to their home wiring connecting to the Grid. For some this will mean 1 CT (single phase) whilst others will be 3 CT (3 phase) used.  

Given this your total_energy and total_power sensors, given they produce a reading for ALL of the CT's will produce an output that is really of no benefit for lots of users (i.e. users will have a total that is made of either 1 grid in/out [Nett] reading  and 5 household circuit readings. Or 3 grid + 3 household circuits, in the case of a 3p install).  In the case where someone uses energy monitor to monitor solar it will be even more interesting (i.e. 1 grid in/out + 1 solar in or in+out if they use a battery + 4 household circuits.  Or 3p would be 3 grid in/out + 3 solar in/out).

4) If using 1 / 3 CT's for grid connections, you need a sensor (would be nice if written into the custom_component) that calculates the Grid Power/Energy Sum (of 1 or 3 CT's) and Grid Power/Energy Total (with ability to then break that out into Today/Yesterday/Week/Month/Year...such as dentra Energy Statistics custom component provides already). C+ isn't in my skillset for writing a component, but from a yaml method this could be done with substitutes to define Grid CT's, that are then 'converted' using template sensors (set to internal), that could then be called in a final template sensors lambda that calls the preceeding substitute's template sensor, so you have id(grid_1).state + id(grid_2).state + id(grid_3).state = total energy or power. If a 1p install then grid_2 / grid_3 will remain at 0, meaning the lamda will end up grid_1 + 0 + 0 and work for 1p (as well as 3p).

5) Utilisation in Home Assistant... I note that a large number of the Energy / Power cards in use now look to having a sensor supplied for Consumption (Import) AND Production (Export) from Grid.  Currently the Power/Energy total sensors work as a Nett sensor (reading + and -), I would suggest that additional sensors are needed for Grid Import and Export, that would be the Nett sensor run through a template sensor (or could it be done in custom component?) such as these quick examples:

```
template:
  - sensor:
      - name: "Grid Power - Import"
        unit_of_measurement: "W"
        state: "{{ max(0, states('sensor.grid_total_power')|float) }}"

      - name: "Grid Power Export"
        unit_of_measurement: "W"
        state: "{{ max(0, -1 * states('sensor.grid_total_power')|float) }}"

```


```
template:
  - sensor:
      - name: "Grid Energy Import"
        unit_of_measurement: "kWh"
        state: "{{ max(0, states('sensor.grid_total_energy')|float) }}"

      - name: "Grid Energy Export"
        unit_of_measurement: "kWh"
        state: "{{ max(0, -1 * states('sensor.grid_total_energy')|float) }}"

```

Wondering if the Athom Energy Monitors really need a 'base' configuration on Github to default to when first installed, but then some additional yaml configs be added for the common scenarios that these devices will be used for, that people can read the online documentation then update their pacakge configuration from pointing to athom-energy-monitor-x6.yaml on Github, to point to (example) athom-energy-monitor-x6-1p-home.yaml, athom-energy-monitor-x6-3p-home.yaml or athom-energy-monitor-x6-1p-home-solar.yaml etc?

PS. Will seea about posting link to friends 3p grid + 3 house circuits when I finish it, to give some ideas.

**Reply by tarontop** [reply]
We checked and found that there is indeed a logical error in the order of the labels, but you said that after connecting the 6 CT calipers correctly, 4 of them produced negative readings. I think this is not accurate. It should all produce negative readings or positive readings.
![image](https://github.com/user-attachments/assets/93a9ce31-f430-461a-be12-e247fec9da35)

**Reply by Roving-Ronin** [reply]
Hi Aiden,

This is a small issue of labelling, thought I'd flag anyhow so other users don't have issues. I'm actually more interested in your feedback and thoughts re the usage scenarios and from this the templates for these devices in regards the sensors that are defined. ???

**Reply by pumo2019** [reply]
> We checked and found that there is indeed a logical error in the order of the labels, but you said that after connecting the 6 CT calipers correctly, 4 of them produced negative readings. I think this is not accurate. It should all produce negative readings or positive readings. ![image](https://private-user-images.githubusercontent.com/37043404/359015915-93a9ce31-f430-461a-be12-e247fec9da35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3MzgyNTMsIm5iZiI6MTczNTczNzk1MywicGF0aCI6Ii8zNzA0MzQwNC8zNTkwMTU5MTUtOTNhOWNlMzEtZjQzMC00NjFhLWJlMTItZTI0N2ZlYzlkYTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAxVDEzMjU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNTYyMTdiNjk2ODRmYmNmYjgzMTkyMjUyNDI5YzNjZWFiZWQxMmNiMDcyM2M3NDhkYmY2ZDUzZTdlZTY3YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bHynPC2RuDFvwAG8b1WG4goSED725MTMt6yaC66hANw)

your CT connection are wrong way, at least what are in little manual what came with meter. In there was to put all reds in S1  and blacks to S2. 
I am also interested that 3phase, I just got this device but it wont work, counts power readings  wrong, ex current is  2,9Amps power is 20-30W (all the time), I have connected  first three (CT1-CT3)  to incoming phases.

**Reply by Roving-Ronin** [reply]
> I am also interested that 3phase, I just got this device but it wont work, counts power readings wrong, ex current is 2,9Amps power is 20-30W (all the time), I have connected first three (CT1-CT3) to incoming phases.

@pumo2019 

The way that the BL09906 component (Docs: https://esphome.io/components/sensor/bl0906.html |  Component Code: https://github.com/esphome/esphome/tree/dev/esphome/components/bl0906 ) is written is 'wrong' (IMHO - Sorry Aiden) as it assumes that ALL the CT's are connected to internal power circuits and then calculates the Total_Energy and Total_Power sensors on this basis.

So if your trying to use the Energy Meter 2/4/6 to monitor:
- 1 Phase - The main/grid feed + 1 internal circuit (say Solar, if you don't have the OEM consumption meter with the inverter)
- 3 Phase - The main/grid feed (3 xCT) + 3 internal circuits (say solar + hot water + GPO)
then this meter, in its current 'from the box' setup from Athom will NOT work, as you desire.

Whilst a total rewrite of the BL0906 component would be great, to add support in the YAML to have a setting for 'is CT internal vs Mains' and then dynamically update the Total_Energy and Total_Power based upon Internal and/or Mains. In the interim you have to work out totally reworking the Energy Meter via YAML.

I have a mate who wanted to use one of these for 3p (Mains and  3 Internal Circuits) monitoring. The code I wrote for him is at: https://github.com/JAComms/MyHomeAssistant/blob/main/esphome/athom-energy-meter-x6.yaml

Note: CT 1/2/3 are connected to Mains Phase 1/2/3 and CT 4/5/6 are used for internal circuits.  If you want to try flashing your device with this, it call be called using the following YAML configuration on your device config. Just update the 'ct_sensor_#_name' subsitutions to reflect what/where you have installed CT4-6.

If @tarontop / @athom-tech wanted to add an 'official' release of this at: https://github.com/athom-tech/esp32-configs i.e. [athom-energy-monitor-x6.yaml](https://github.com/athom-tech/esp32-configs/blob/main/athom-energy-monitor-x6-3phase.yaml) ?

Sorry I don't have access to mates device currently, otherwise I'd paste a screenshot of the updated webserver and sensors.

```
substitutions:
  name: "energy-meter"
  # Default friendly name
  friendly_name: "Energy Meter"
  # Description as appears in ESPHome & top of webserver page  
  device_description: "Athom - Energy Meter (BL0906 - 6 channels)"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  location: "Switchboards"
  # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO 1 = Phase C, GPO 2 = Phase A, GPO 3 = Phase B)
  power_circuit: "Phase B"  # Which power cicruit is actually powering this device?
  # Hide, by making 'internal', the individual CT's energy sensors
  hide_surplus_energy_sensors: "true"

  # Define logging level: NONE, ERROR, WARN, INFO, DEBUG (Default), VERBOSE, VERY_VERBOSE
  log_level: "DEBUG"

  # Disable sensors recording Grid EXPORTS (i.e. house with no solar installed)
  disable_grid_export_sensors: "true"

  # Names to describe the usage of each CT sensor. i.e. Lights, GPO1, Grid etc. Used to prefix all the associated sensors.
  ct_sensor_1_name: "Grid Phase A"  # CT 1
  ct_sensor_2_name: "Grid Phase B"  # CT 2
  ct_sensor_3_name: "Grid Phase C"  # CT 3
  ct_sensor_4_name: "Kitchen"         # CT 4
  ct_sensor_5_name: "Caravan"         # CT 5
  ct_sensor_6_name: "Float Charger"   # CT 6

#########################################################################

esphome:
  name_add_mac_suffix: false

#########################################################################
#
# Remote Packages to be utilised
#

packages:
  remote_package:
    url: https://github.com/JAComms/myHomeAssistant/
    ref: main 
    files: [esphome/athom-energy-meter-x6.yaml]
    refresh: 0s # optional


#####################################################################

```
