### DISCUSSION TITLE
ESP32-C3 devices as BLE Proxies

### DISCUSSION THREAD

**Discussion by DJBenson** [athom-tech/esp32-configs#20] [General]
If like me you want to use your Athom ESP32-C3 devices as BLE proxies then you'll probably know you can't do this without switching to the esp-idf framework and (generally) you can't do that OTA, it's recommended you do it via serial which is not possible with certain devices due to them being sealed units.

I have just managed to convert my UK v3 smart plug from the arduino framework to the esp-idf framework OTA - instructions below;

Amend your existing config to include the snippet below;

```
esp32:
  framework:
    type: esp-idf
  flash_size: 4MB
  partitions: "partitions.csv"
``` 

Create a file named partitions.csv in the root of your esphome directory with the following content;
```
padding, data, undefined,    ,       0x4000,
phy_init, data, phy,     ,        0x1000,
otadata,  data, ota,     ,        0x2000,
app0,     app,  ota_0,   ,        0x1C0000,
app1,     app,  ota_1,   ,        0x1C0000,
nvs,      data, nvs,     ,        0x6D000,
```

Build and flash the firmware OTA.

Once the device has rebooted, build and flash it **again**! This replaces the secondary OTA slot with the new partition scheme.

Some notes;
- Do this at your own risk - if you brick these devices there is no non-destructive way to fix them
- You will lose the ability to flash the devices via the web portal as that isn't supported by the esp-idf framework.

Since doing this my tumble dryer smart plug has started relaying BLE traffic to Home Assistant which it didn't before.

**Comment by pyrodex** [comment]
First off great work and write-up!

For the comment:
> * You will lose the ability to flash the devices via the web portal as that isn't supported by the esp-idf framework.

Can you explain this? I would assume you can still, from the ESPHome dashboard, do a normal ESPHome based update via OTA right?

**Reply by DJBenson** [reply]
Yeah it's just the upload firmware capability of the web portal you lose. I use this for rescue purposes but it's mostly not required. 

I expect this will be fixed soon as the esp-idf framework appears to be on the way to becoming the default framework.

**Comment by TommySharpNZ** [comment]
Awesome, thanks for sharing this...

**Comment by laurentfignon** [comment]
Thank you and this seems super but I have a question -- does the rest of your config still work the same as before converting to esp-idf?

**Reply by DJBenson** [reply]
With the exception of losing the webflash option yes.

**Reply by laurentfignon** [reply]
Got this working thanks to your help -- I'm finding that it's not nearly as responsive as a m5 atom lite device, though.  Seems to maybe not be maintaining a BLE connection, rather re-negotiating it each time it's needed.  Is this anyone else's experience?  If not, any ideas what's going on?  Thank you!

**Comment by dexn** [comment]
@DJBenson May I ask how your YAML looks like? When compiling I'm getting a whole heap of errors like
```
/config/esphome/athom-smart-plug-v3-b0b8b4.yaml: In lambda function:
/config/esphome/athom-smart-plug-v3-b0b8b4.yaml:361:30: error: no matching function for call to 'std::__cxx11::basic_string<char>::basic_string(int&)'
  361 |         return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
      |                              ^
In file included from /data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/12.2.0/string:53,
                 from /data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/12.2.0/bits/locale_classes.h:40,
                 from /data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/12.2.0/bits/ios_base.h:41,
                 from /data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/12.2.0/ios:42,
                 from /data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/12.2.0/ostream:38,
                 from /data/cache/platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/12.2.0/bits/unique_ptr.h:41,
```

**Reply by tjharman** [reply]
Yea that's what I'm finding too, sadly.

**Comment by DJBenson** [comment]
My devices are still using this config and I'm not getting these errors. Have you tried cleaning the build files and compiling from fresh?

**Reply by tjharman** [reply]
Yup - straight away I get errors. This is what my .yaml looks like:

```
substitutions:
  name: athom-smart-plug-v3-b0c820
  friendly_name: Garage Smartplug
packages:
  Athom_Technology.Smart_Plug_V3: github://athom-tech/esp32-configs/athom-smart-plug.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
esp32:
  framework:
    type: esp-idf
  flash_size: 4MB
  partitions: "partitions.csv"

api:
  encryption:
    key: <key>

esp32_ble_tracker:
   scan_parameters: 
      continuous: true
      active: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

**Reply by tjharman** [reply]
Sorry I also need to be very clear - I don't think it's _anything_ to do with the config you've suggested DJBenson.  Only probably there's a newer version of esp-idf being pulled for me than you have cached, and it's got some issue.  I have total faith your suggestion is legit :)

**Reply by DJBenson** [reply]
If you go to the devices page in ESPHome then click the three dots of the device and then "Validate" then scroll down to the esp32: node, it should tell you the version of the framework it's pulling. This is mine;

```
esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  variant: ESP32C3
  framework:
    version: 5.1.6
    sdkconfig_options: {}
    advanced:
      ignore_efuse_custom_mac: false
    components: []
    platform_version: https://github.com/pioarduino/platform-espressif32.git#51.03.07
    source: pioarduino/framework-espidf@https://github.com/pioarduino/esp-idf/releases/download/v5.1.6/esp-idf-v5.1.6.zip
    type: esp-idf
  partitions: partitions.csv
  cpu_frequency: 160MHZ
```

So esp-idf 5.1.6.

I'm running ESPHome 2025.5.1.

**Reply by DJBenson** [reply]
Is that the full YAML you posted? I've chucked the error into ChatGPT along with my error and it seems to think it would be coming from a lambda which I use to return the uptime of the device in human readable form but that won't apply to you unless you're doing exactly the same thing - and in any case mine is still compiling.

**Comment by tjharman** [comment]
Yea I've got the same versions.
If you look at my config, it's just the default Athom one.
Which means it's also pulls in the config from here:

github://athom-tech/esp32-configs/athom-smart-plug.yaml (which is really https://raw.githubusercontent.com/athom-tech/esp32-configs/refs/heads/main/athom-smart-plug.yaml)

And that's where the Lamba function is.

Do you still have the line 

```
packages:
  Athom_Technology.Smart_Plug_V3: github://athom-tech/esp32-configs/athom-smart-plug.yaml
```
in your config?

Also: Thank you for taking your time to help debug this!!

**Reply by DJBenson** [reply]
I've kinda got my own format for ESPHome config. This is mine (which won't make much sense as it's modular 😄);

```
substitutions:
  devicename: "tumble-dryer"
  devicename_upper: "Tumble Dryer"
  main_icon: "tumble-dryer"
  project_name: "athom.smart-plug-v3"
  project_version: "1.0.1"
  default_state: ALWAYS_ON
  activity_threshold: "5"
  decimal_resolution: "1"
  sensor_update_interval: 10s
  current_limit: "13"
  wifi_fast_connect: "false"
  log_level: INFO
  web_server_version: "3"

packages:
  # WiFi (WLAN config, captive portal, Improv serial, WiFi sensors etc.)
  wifi: !include .wifi.yaml
  # Base configuration (OTA, default sensors etc.)
  device_base: !include .base.yaml
  # Device specific configuration
  device_main: !include .athomsmartplugv3.yaml
  state_sensor: !include .statesensor.yaml
  # BLE tracker !ESP32 Only!
  ble_tracker: !include .ble_tracker.yaml
  # BLE proxy !ESP32 Only!
  ble_proxy: !include .ble_proxy.yaml

<<: !include .idf-partition.yaml
```

It means I can use standard components for all my devices and just include a device-specific file for anything unique to the device.

My config inherits that lambda from base.yaml here;

```
esphome:
  friendly_name: "${devicename_upper}"

# Enable logging
logger:
  level: ${log_level}

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Enable web server on default port
web_server:
  port: 80
  version: ${web_server_version}

# Enable OTA uploads
ota:
  - platform: esphome
    password: !secret ota_password

debug:
  update_interval: 30s

sensor:
  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    update_interval: 60s
    entity_category: diagnostic
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

text_sensor:
  - platform: template
    name: "Uptime Human Readable"
    id: uptime_human
    icon: mdi:clock-start
    entity_category: diagnostic
  - platform: debug
    reset_reason:
      name: "Reset Reason"
      entity_category: diagnostic
  - platform: version
    name: "ESPHome Version"
    entity_category: diagnostic
    
button:
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: factory_reset
    name: "Factory Reset"
    id: Reset

time:
  - platform: homeassistant
    id: homeassistant_time
```
