### ISSUE TITLE
Athom Energy Meter 6CH not compiling with esp-idf

### ISSUE THREAD

**Issue by jcastro** [athom-tech/esp32-configs#37]
Hi!  
I'm trying to compile [this config](https://github.com/athom-tech/esp32-configs/blob/main/athom-energy-monitor-x6.yaml) with the esp-idf framework to enable BT Proxy and BLE, but it's throwing many errors. Is it not compatible, or should I change something else aside from the framework line? This is how my `esp32:` looks like; the rest is the same

```
esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  variant: ESP32C3
  framework:
    type: esp-idf
    #version: recommended
```

Thanks!
