### ISSUE TITLE
v3 Plug - UART Parity Setting Error

### ISSUE THREAD

**Issue by Roving-Ronin** [athom-tech/esp32-configs#9]
@athom-tech 

With the default config on the v3 plug of:
```
uart:
  rx_pin: GPIO20
  baud_rate: 4800
  data_bits: 8
  stop_bits: 1
  parity: EVEN
```
When booting I notice the following error:

   [E][uart:029]:   Invalid parity: Integration requested parity NONE but you have EVEN!

Is this setting correct, or should it be:

```
uart:
  rx_pin: GPIO20
  baud_rate: 4800
  data_bits: 8
  stop_bits: 1
  parity: NONE
```
